services:
  app:
    build:
      context: .
      args:
        - DEV=true
    ports:
      - "8000:8000"
    volumes:
      - ./djackets_django:/djackets_django
    command: >
      sh -c "python manage.py runserver 0.0.0.0:8000"
